name: Lenzart Photography
favicon: null
layout_spectrum: 0.019955340307205915
typography_spectrum: 0.6246990286745131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2531586375553161
  lightness: 0.6208715420216322
  saturation: 0.2632206298876554
  rhythmicContrast: 0.9212404671125114
purpose: []
