name: Lenzart Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60253
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#fefefe'
    - '#c2c2c2'
    - '#707070'
    - '#969696'
  brandStrength: 0.2531586375553161
  lightness: 0.6208715420216322
  saturation: 0.2632206298876554
  rhythmicContrast: 1
purpose: []
